name: dailybox
description: "DailyBox - A minimalist daily utility app with notes, budget tracking, QR codes, link shortener, and file converter."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3
  
  # HTTP Requests
  http: ^1.2.1
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # File Operations
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  path: ^1.9.0
  pdf: ^3.10.8
  
  # Location Services
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  
  # Modern UI Effects
  liquid_glass_renderer: ^0.1.1-dev.11
  glassmorphism: ^3.0.0
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  blur: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
